#!/usr/bin/env bash
# ==============================================================================
# Script to pull, update, and manage AzerothCore modules
# Supports:
#   ./tools/pull_modules.sh              -> Pulls/restores tested STABLE commits (Default)
#   ./tools/pull_modules.sh --stable     -> Explicitly check out stable commits
#   ./tools/pull_modules.sh --stable <m> -> Roll back a single module to stable
#   ./tools/pull_modules.sh --latest     -> Pulls bleeding-edge latest branches
#   ./tools/pull_modules.sh --latest <m> -> Pulls latest branch for a single module
#   ./tools/pull_modules.sh --freeze     -> Saves current working commits to lockfile
# ==============================================================================
set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "${SCRIPT_DIR}/.." && pwd)"
MODULES_DIR="${REPO_ROOT}/modules"
CONF_DIST="${REPO_ROOT}/conf/dist/modules.list"
CONF_FILE="${REPO_ROOT}/conf/modules.list"
LOCK_FILE="${REPO_ROOT}/conf/dist/modules.lock"

MODE="stable"
TARGET_MOD=""

# Parse arguments
while [ $# -gt 0 ]; do
  case "$1" in
    --stable)
      MODE="stable"
      shift
      if [ -n "$1" ] && [[ ! "$1" =~ ^-- ]]; then
        TARGET_MOD="$1"
        shift
      fi
      ;;
    --latest)
      MODE="latest"
      shift
      if [ -n "$1" ] && [[ ! "$1" =~ ^-- ]]; then
        TARGET_MOD="$1"
        shift
      fi
      ;;
    --freeze)
      MODE="freeze"
      shift
      ;;
    -h|--help)
      echo "Usage: $0 [--stable [mod_name] | --latest [mod_name] | --freeze]"
      echo ""
      echo "Options:"
      echo "  (no args)          Default: Fetch and check out known stable tested commits"
      echo "  --stable [mod]     Ensure all (or specific) modules match the stable lockfile"
      echo "  --latest [mod]     Pull bleeding-edge default branch from upstream remotes"
      echo "  --freeze           Update conf/dist/modules.lock with current working commits"
      exit 0
      ;;
    *)
      if [ -z "${TARGET_MOD}" ]; then
        TARGET_MOD="$1"
      fi
      shift
      ;;
  esac
done

# Freeze mode handler
if [ "${MODE}" = "freeze" ]; then
  echo "======================================================================"
  echo "Freezing current module commits to: ${LOCK_FILE}"
  echo "======================================================================"
  
  cat << 'HEADER' > "${LOCK_FILE}"
# ==============================================================================
# AzerothCore Modules Lockfile (Tested & Known-Working Commits)
#
# Generated by: ./tools/pull_modules.sh --freeze
# Use ./tools/pull_modules.sh (or --stable) to restore these commits.
# Use ./tools/pull_modules.sh --latest to pull bleeding-edge upstream versions.
# ==============================================================================

HEADER

  frozen=0
  for mod_dir in "${MODULES_DIR}"/*/; do
    if [ -d "${mod_dir}/.git" ]; then
      mod_name="$(basename "${mod_dir}")"
      mod_url="$(git -C "${mod_dir}" config --get remote.origin.url 2>/dev/null || echo "")"
      mod_commit="$(git -C "${mod_dir}" rev-parse HEAD 2>/dev/null || echo "")"
      if [ -n "${mod_url}" ] && [ -n "${mod_commit}" ]; then
        echo "${mod_url} ${mod_commit}" >> "${LOCK_FILE}"
        echo "  [✓] ${mod_name} -> ${mod_commit}"
        frozen=$((frozen + 1))
      fi
    fi
  done

  echo ""
  echo "Frozen ${frozen} module commit(s) into lockfile."
  exit 0
fi

# Ensure configuration file exists
if [ ! -f "${CONF_FILE}" ]; then
  if [ -f "${CONF_DIST}" ]; then
    echo "Creating initial ${CONF_FILE} from template..."
    cp "${CONF_DIST}" "${CONF_FILE}"
  else
    echo "Error: Config file not found at ${CONF_FILE}" >&2
    exit 1
  fi
fi

mkdir -p "${MODULES_DIR}"

total=0
processed=0
warnings=0

echo "======================================================================"
echo "Module Management Mode: ${MODE^^}"
if [ -n "${TARGET_MOD}" ]; then
  echo "Target Module:          ${TARGET_MOD}"
fi
echo "Configuration:          ${CONF_FILE}"
echo "Lockfile:               ${LOCK_FILE}"
echo "Target Directory:       ${MODULES_DIR}"
echo "======================================================================"

while IFS= read -r line || [ -n "${line}" ]; do
  # Strip whitespace
  line="$(echo "${line}" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')"

  # Skip comments and empty lines
  if [ -z "${line}" ] || [[ "${line}" =~ ^# ]]; then
    continue
  fi

  total=$((total + 1))

  # Parse line
  read -r repo_url custom_ref _ <<< "${line}"
  mod_name="$(basename "${repo_url}" .git)"
  mod_path="${MODULES_DIR}/${mod_name}"

  # Filter if target mod specified
  if [ -n "${TARGET_MOD}" ] && [ "${TARGET_MOD}" != "${mod_name}" ]; then
    continue
  fi

  processed=$((processed + 1))
  echo ""
  echo "[${processed}] Processing: ${mod_name}"

  # Find locked commit if in stable mode
  locked_commit=""
  if [ "${MODE}" = "stable" ]; then
    if [ -n "${custom_ref}" ]; then
      locked_commit="${custom_ref}"
    elif [ -f "${LOCK_FILE}" ]; then
      locked_commit="$(grep -E "^[[:space:]]*${repo_url}[[:space:]]+" "${LOCK_FILE}" | awk '{print $2}' | head -n1 || echo "")"
    fi
  fi

  # Module directory does not exist: clone it
  if [ ! -d "${mod_path}" ]; then
    if [ "${MODE}" = "stable" ] && [ -n "${locked_commit}" ]; then
      echo "  -> Cloning and pinning to stable commit: ${locked_commit}"
      git clone "${repo_url}" "${mod_path}"
      (cd "${mod_path}" && git checkout "${locked_commit}")
    else
      echo "  -> Shallow cloning latest default branch (--depth 1)..."
      git clone --depth 1 "${repo_url}" "${mod_path}"
    fi
    continue
  fi

  # Module directory exists: update or switch commit
  if [ ! -d "${mod_path}/.git" ]; then
    echo "  [WARN] ${mod_path} is not a git repository. Skipping."
    warnings=$((warnings + 1))
    continue
  fi

  if [ "${MODE}" = "stable" ]; then
    if [ -n "${locked_commit}" ]; then
      current_head="$(git -C "${mod_path}" rev-parse HEAD 2>/dev/null || echo "")"
      if [ "${current_head}" = "${locked_commit}" ]; then
        echo "  -> Already at locked commit (${locked_commit:0:8})."
      else
        echo "  -> Checking out stable commit: ${locked_commit}..."
        if ! git -C "${mod_path}" checkout "${locked_commit}" 2>/dev/null; then
          echo "  -> Commit not found locally. Fetching from origin..."
          git -C "${mod_path}" fetch origin
          git -C "${mod_path}" checkout "${locked_commit}"
        fi
        echo "  -> Successfully pinned to ${locked_commit:0:8}."
      fi
    else
      echo "  -> No lock found. Fast-forwarding default branch..."
      git -C "${mod_path}" pull --ff-only 2>/dev/null || true
    fi
  else
    # Latest mode
    echo "  -> Fetching bleeding-edge upstream..."
    current_branch="$(git -C "${mod_path}" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "")"
    if [ "${current_branch}" = "HEAD" ]; then
      # If detached HEAD from stable mode, switch back to master/main
      default_branch="$(git -C "${mod_path}" symbolic-ref refs/remotes/origin/HEAD 2>/dev/null | sed 's@^refs/remotes/origin/@@')"
      [ -z "${default_branch}" ] && default_branch="master"
      git -C "${mod_path}" checkout "${default_branch}" 2>/dev/null || git -C "${mod_path}" checkout main 2>/dev/null || true
    fi
    if git -C "${mod_path}" pull --ff-only 2>/dev/null; then
      echo "  -> Updated to latest commit."
    else
      echo "  [WARN] Could not fast-forward ${mod_name}. Skipping to protect local changes."
      warnings=$((warnings + 1))
    fi
  fi
done < "${CONF_FILE}"

echo ""
echo "======================================================================"
echo "Finished processing ${processed} module(s). (Warnings: ${warnings})"
echo ""
echo "Tips:"
echo "  - If a build fails after pulling latest, roll back with: ./tools/pull_modules.sh --stable"
echo "  - After updating modules, re-run cmake: cd build && cmake .. && make -j$(($(nproc) - 2))"
echo "======================================================================"
